// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zawxvyxgitguvcnqarys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inphd3h2eXhnaXRndXZjbnFhcnlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1MzQwOTgsImV4cCI6MjA1MjExMDA5OH0.yQPOJJ3QFncH7L_3XMIi1uYcE2uhyW5wOcnOn98-UQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);